### ISSUE TITLE
PyPI listing

### ISSUE THREAD

**Issue by bbayles** [nkapowski/qs_vod_metadata#1]
Could you please remove my name from the **Author** field in the PyPI listing for `qs_vod_metadata`?
https://pypi.python.org/pypi/qs_vod_metadata/2016.1.6

It's great that you're making your own version of `vod_metadata`, but please do not use my name in conjunction with your version.

You should also update the copyright information in the license; see [here](http://programmers.stackexchange.com/a/277699/144304) for an example of what to put.

**Comment by nkapowski** [comment]
Hi Bo, Based on the license provided I put myself as maintainer and kept you as author.
Sorry if it is cause and inconvenience. I will update project license based on what you asking and remove your name from it.
Thanks for your great product and sorry if any inconvenience cause.
